name: CI

on:
  pull_request:
    branches:
      - 'develop'

jobs:

  CI:
    name: "CI"
    runs-on: windows-2022
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} 
          repository: YoYoGames/YoYoPerformanceAndTestSuite
          event-type: html5-pr
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
